### PR TITLE
Resolves #62 - Adds update to help menu after switcher is connected

### LINKED ISSUE #62: no osc sources
hi
there i've setup atemOSC with my ATEM Television Studio HD, I've a trouble to get the OSC adresses for sources, when I clic on OSC adresses in Help menu he don't give me the sources.
I setup with your default instruction for the cam 1 to 8 and it's working, but can't work for media player, color or bar (works for black).
Do you have any idea why I can't get the OSC adresses ?
thanks

### PR DESCRIPTION
**Pull request by SteffeyDev**
This is untested, but technically should work.  I won't be able to test until Sunday, so am putting this up in case someone can test before then.

All it does is re-load the help menu at the end of switcherConnected.

### CODE REVIEW

**Comment by SteffeyDev** [comment]
Just looked in the code again, and realized that the sources section is actually gone from the source code.  I'm going to look through git history later to see if I can find it.

**Comment by SteffeyDev** [comment]
Ok, so I fixed #62 officially and tested, I'll merge this in tomorrow pending any additional reviews/tests.

**Comment by sneat** [comment]
Looks good. Did you want to build a new version at all and we'll merge it in?

**Comment by SteffeyDev** [comment]
@sneat I always forget about that part, it's there now.

**Pull request merged**
