### PR TITLE
Full Code Base Refactor

### PR DESCRIPTION
**Pull request by SteffeyDev**
This splits the main file (`SwitcherPanelAppDelegate.h/mm`) into three files (`AppDelegate.h/mm`, `FeedbackMonitors.h/mm`, and `OSCReceiver.h/mm`).  This makes the code much more manageable and logically organized.

In addition, the entire tally interface is removed per #42, which makes the code base much simpler and the UI easier for new users to reason about (hopefully)

Lastly, the code was standardized, and repetitive code was extracted into functions.  The coding standard I went with was brackets on their own line (the project was half and half before), let me know if this isn't acceptable @danielbuechele.

I'm really hoping with the slimmed down and focused code base, new features will be easy to add and verify.  I'm working on creating a TouchOSC layout for testing that can run every command available, and I'll include that with this PR when its done.

I basically changed almost every line in the project, so I wanted to open this for @sneat and @danielbuechele to start reviewing, even though it's not completely tested and ready to merge yet.

Let me know how you feel about where I've put different components of the project, the various names of files, and the other changes I have made.

TODO:
- [x] Fix crash when using DSK's other than 1
- [x] Add full testing layout to repository
- [x] Update testing layout to include Aux
- [x] Update README to remove parts about Arduino Tally Interface
- [x] Test all commands to make sure they still work after changes
- [x] Fix OSC address list to include all from README (Moved to #49)

### CODE REVIEW

**Comment by sneat** [comment]
That's an impressive refactor. I don't have ready access to an ATEM currently, so won't be able to actually test it for a while.

**Comment by SteffeyDev** [comment]
@sneat I'll go ahead and test, it'd be great if you could read over some of the code to make sure I'm doing things right.  For example, in `FeedbackMonitors` I'm using a static cast to convert the `void*` to `AppDelegate*` to make calls on, but I don't know if that is the best way.

**Comment by sneat** [comment]
@SteffeyDev understood, I'll try take a look at some point 👍

**Comment by danielbuechele** [comment]
Can’t really have a look on it in the next days. Just wanted to let you
know that you can feel free to change the structure as you like. No hard
feelings about a certain code style or anything.
I think you refactor is amazing and really needed, thank you!

On Oct 9, 2017, at 4:52 AM, Blair <notifications@github.com> wrote:

@SteffeyDev <https://github.com/steffeydev> understood, I'll try take a
look at some point 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/danielbuechele/atemOSC/pull/44#issuecomment-335062578>,
or mute the thread

**Comment by SteffeyDev** [comment]
Ok, I tried my hand at redoing the UI a bit, but not sure if it is actually any better.  I'll let you guys take a look at it when you get the chance, and I'd be fine dropping it if it's more confusing or not an improvement.

I can't finish testing until next Sunday so no rush on the reviews

**Comment by danielbuechele** [comment]
screen shot 2017-10-10 at 12 07 12

In general I like cleaning the UI, some comments: 
- perhaps we should add some placeholders
- all textfields should be aligned
- I don't like the headings, they look so non macOS-like
- perhaps we should somehow make switcher name not a textfield, because it is not editable

**Comment by SteffeyDev** [comment]
I like the idea of a menu bar app, I’m imagining it having four “rows” in the dropdown:
* Status row [active|inactive]
* Log
* OSC Addresses
* Settings

Where the log and addresses would pull up windows similar to what they do now, and the settings would pull up a window sort of like this one but maybe with two tabs instead of the headings? I feel like tabs would be more macOS-like. And then on launch, if any values are not entered, the settings panel would launch automatically. 

What are your thoughts? And would this be something you want to take on or should I take a stab at it?

**Comment by SteffeyDev** [comment]
On that note, I’m going to drop the last commit and create a new issue for the UI redesign.

**Comment by danielbuechele** [comment]
Yes, let's separate the refactor and UI overhaul. I can work a little on the menubar app

**Comment by danielbuechele** [comment]
Perhaps we could move the code for the windows out of the AppDelegate, so there are separate files for MainWindow, Logs and addresses. What do you think?

**Comment by SteffeyDev** [comment]
We certainly could, I'm assuming this would help simplify your UI redesign?

**Comment by danielbuechele** [comment]
Yes, that would make things easier. If it’s not too much work for you I would appreciate it.

**Comment by SteffeyDev** [comment]
@danielbuechele Ok, I think this is ready to merge in. I tested everything except for Aux and Supersource, but I have not changed the code for either, only moved it, so no reason they should not work.  I'll let you merge this after checking the commits, let me know if I should squash any.

**Comment by danielbuechele** [comment]
Nice, also tried it and everything seems to work fine.

**Pull request merged**
