### PR TITLE
Support for send-status OSC Command and Macro Feedback

### PR DESCRIPTION
**Pull request by SteffeyDev**
I've added a command `/atem/send-status` that, when triggered, has each of the feedback monitors query the switcher and send it's current status.  Thus, only program/preview and DSK/USK is currently supported, but support can be added as more feedback is added.

Let me know how you feel about `send-status`, I am open to change.

This is very useful for TouchOSC, because when you switch tabs it can trigger an OSC Send.  So when I open TouchOSC on a new iPad during production and switch to the video tab, it automatically sends `/atem/send-status`, which then updates my TouchOSC interface with the currently selected options.

In addition to this, Macro feedback was enabled, so send-status can also load up the macro names and descriptions.  A small API change was made, changing `/atem/macros/get-max-number` to just `/atem/macros/max-number` (though still backward compatible), because with feedback this command is now a two-way bind (not just a get).

To implement the macro feedback, it was necessary to move the macro utility functions from `OSCReceiver` to a new `Utilities` file that is imported by both `OSCReceiver` and `FeedbackMonitors`.  Other utility functions were also moved to this new file.

### CODE REVIEW

**Comment by sneat** [comment]
That's a good idea. Would you be able to add a sample implementation for TouchOSC into the samples directory too?

**Comment by SteffeyDev** [comment]
That's also a great idea, I updated the samples to call /atem/send-status for every tab change

**Comment by SteffeyDev** [comment]
@sneat @danielbuechele Added macro feedback support to this and made some file structure changes to accommodate, just tested today and everything works as expected.

**Comment by SteffeyDev** [comment]
I'll leave this open for another day or two in case @sneat wants to review the changes and then merge

**Comment by sneat** [comment]
Looks good to me.

Haven't had a chance to actually compile and test it, but the code changes look good.

**Comment by SteffeyDev** [comment]
@danielbuechele How do you feel about merging this and then releasing 2.5? I had wanted to wait for your menu bar changes but it sounds like those will take a bit longer, and we now have 3 bug fixes that need to be released.

**Comment by danielbuechele** [comment]
Sure, let’s ship 2.5 without the menu bar.

**Pull request merged**
