### PR TITLE
Issue #55 - Audio Controls (initial code)

### PR DESCRIPTION
**Pull request by SteffeyDev**
This PR adds the base support for audio controlling, allowing for the control of the gain and balance on each of the inputs and the mix output.  It adds the appropriate feedback, updates the sample TouchOSC layout, and adds audio to the in-app OSC address list.

In addition, I took the liberty to change up the send-status behavior a bit, to ensure that each feedback monitor has the appropriate time to send the status that it needs to.  Adding audio feedback required a better control system, and thus it was included here.

One point for discussion: Should the external audio inputs be addressed by index or by their input ID?  For example, if the 8 camera audio inputs are indexed 1-8 and have corresponding input IDs, but the external audio is indexed 9-10 but has input IDs of 1001 and 1201, should the API be `/atem/audio/input/9/gain` or `/atem/audio/input/1001/gain`?

### CODE REVIEW

**Comment by sneat** [comment]
Looks good so far.

**Comment by SteffeyDev** [comment]
The camera input ID already matches the audio input ID, that's a built-in feature as far as I know

**Comment by sneat** [comment]
Ahh right, in that case I think it maybe have the camera inputs as they are 1-8 (or 1-20 etc), and have the external inputs as their actual ids (1001 and 1201).

Otherwise the audio input changes depending on your device (9-10 on a TVS, 21-22 on a ME/2 etc).

**Comment by SteffeyDev** [comment]
Ok, the latest version uses `std::map` so that audio controls are via actual input IDs instead of arbitrary array indices.  It has been tested and provides feedback and meaningful error logs if they mess up the command.

**Comment by SteffeyDev** [comment]
@sneat Because this is a large change, I would appreciate a second person testing it if you have the chance sometime.

**Comment by sneat** [comment]
I like that change to make it a map. I'm not sure that I'll get a chance to test it anytime soon though sorry.

**Comment by SteffeyDev** [comment]
That's Ok, because this is a new feature, no one is currently using it, so it's not like this change can break anything.  We'll see if we get any feedback when people start testing with other devices.  I'll merge if there is no more activity in the next few days.

**Pull request merged**
