### PR TITLE
Resolves #50 - Aux Fix

### LINKED ISSUE #50: AUX Switching not functioning
I have been unable to make the AUX switching function work,
I wish to switch an input to an AUX channel. 

AtemOSC 2.4.7

Using Sample Template ( Advanced Video Control ) or building my own.

Set Aux $i source to $x /atem/aux/$i $x
Where $x is a valid program source. Check the Help Menu for the correct values.
e.g. /atem/aux/1 1 to set Aux 1 output to source 1 (Camera 1)
(up to /atem/aux/6 $x, depends on your ATEM switcher)

Is this currently functioning?

### PR DESCRIPTION
**Pull request by SteffeyDev**

### CODE REVIEW

**Comment by danielbuechele** [comment]
Looks good! However, indentation seems to be using space, whereas other parts are using tabs. I don't care what we are using, but it should be consistent.

**Comment by SteffeyDev** [comment]
Oh it looked funny, that explains why.  Very odd, still using Xcode... I'll fix

**Comment by SteffeyDev** [comment]
Ok turns out half the project was tabs, half was spaces... Now fixed, re-tabed all files

**Comment by sneat** [comment]
The change looks good.

Have we extracted the bundled app out completely? Otherwise can you build and include the app with the fix?

**Comment by SteffeyDev** [comment]
@sneat That's a good idea, I included the latest binary in a new commit

**Comment by SteffeyDev** [comment]
@sneat @danielbuechele Do you think this is ready to merge?

**Comment by danielbuechele** [comment]
Looks good to me.

On Oct 31, 2017, at 12:34 AM, SteffeyDev <notifications@github.com> wrote:

@sneat <https://github.com/sneat> @danielbuechele
<https://github.com/danielbuechele> Do you think this is ready to merge?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/danielbuechele/atemOSC/pull/51#issuecomment-340625160>,
or mute the thread

**Pull request merged**
